---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-user-catalog-access
  annotations:
    description: >-
      Access to Babylon catalog resources.
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    {{- include "babylon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.catalog.api.group }}
  resources:
  - catalogitems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - template.openshift.io
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
