---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-workshop-admin
  annotations:
    description: >-
      Access to manage workshops and provisions for workshops.
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    {{- include "babylon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.catalog.api.group }}
  resources:
  - workshops
  - workshopprovisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
  - update
