{{- if .Values.smtp.account }}
{{- if .Values.smtp.account.generateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babylon-notifier.smtpSecret" . | quote }}
  namespace: {{ include "babylon-notifier.namespaceName" . }}
  labels:
    {{- include "babylon-notifier.labels" . | nindent 4 }}
data:
  smtp_account: {{ required ".Values.smtp.account.username is required!" .Values.smtp.account.username | b64enc }}
  smtp_password: {{ required ".Values.smtp.account.password is required!" .Values.smtp.account.password | b64enc }}
{{- end }}
{{- end }}
