{{- if (.Values.smtp.account).generateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babylon-notifier.smtpSecret" . | quote }}
  namespace: {{ include "babylon-notifier.namespaceName" . }}
  labels:
    {{- include "babylon-notifier.labels" . | nindent 4 }}
data:
  user: {{ required ".Values.smtp.account.username is required!" .Values.smtp.account.username | b64enc }}
  password: {{ required ".Values.smtp.account.password is required!" .Values.smtp.account.password | b64enc }}
{{- end }}
