{{- if (.Values.smtp.tls).crt }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.smtp.tls.clientCertificateSecret | default (include "babylon-notifier.name" .) }}-tls
  namespace: {{ include "babylon-notifier.namespaceName" . }}
  labels:
    {{- include "babylon-notifier.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.smtp.tls.crt | b64enc }}
  tls.key: {{ required "smtp.tls.key is required when smtp.tls.crt is provided" .Values.smtp.tls.key | b64enc }}
{{ end }}
