{{ if .Values.smtp.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babylon-notifier.name" . }}-tls
  namespace: {{ include "babylon-notifier.namespaceName" . }}
  labels:
    {{- include "babylon-notifier.labels" . | nindent 4 }}
data:
  tls.crt: {{ required ".Values.smtp.tls.crt is required!" .Values.smtp.tls.crt | b64enc }}
  tls.key: {{ required ".Values.smtp.tls.key is required!" .Values.smtp.tls.key | b64enc }}
{{ end }}
