{{ if .Values.smtp.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babylon-notifier.name" . }}-tls
  namespace: {{ include "babylon-notifier.namespaceName" . }}
  labels:
    {{- include "babylon-notifier.labels" . | nindent 4 }}
data:
  {{- if (.Values.smtp.tls).ca }}
  ca.crt: {{ .Values.smtp.tls.ca | b64enc }}
  {{- end }}
  {{- if (.Values.smtp.tls).crt }}
  tls.crt: {{ .Values.smtp.tls.crt | b64enc }}
  {{- end }}
  {{- if (.Values.smtp.tls).key }}
  tls.key: {{ .Values.smtp.tls.key | b64enc }}
  {{- end }}
{{ end }}
