{{ if .Values.db }}
apiVersion: v1
kind: Secret
metadata:
  name: gpte-db-secrets
  namespace: {{ include "babylon-catalog-manager.namespaceName" . }}
  labels:
    {{- include "babylon-catalog-manager.labels" . | nindent 4 }}
data:
  dbname: {{ required ".Values.db.name is required!" .Values.db.name | b64enc }}
  username: {{ required ".Values.db.username is required!" .Values.db.username | b64enc }}
  password: {{ required ".Values.db.password is required!" .Values.db.password | b64enc }}
  hostname: {{ required ".Values.db.hostname is required!" .Values.db.hostname | b64enc }}
  port: {{ required ".Values.db.port is required!" .Values.db.port | b64enc }}
{{ end }}