{{- if .Values.salesforceApi.deploy }}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .Values.salesforceApi.secretName | default "babylon-catalog-manager-salesforce-api" }}
  namespace: {{ include "babylon-catalog-manager.namespaceName" . }}
spec:
  data:
    salesforce-api-token: 
      secret: salesforce_api_login_token
      key: service_token
{{- end }}