{{- if .Values.oauthProxy.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babylonCatalog.oauthProxyClientSecretName" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
data:
  clientSecret: {{ .Values.oauthProxy.clientSecret | b64enc }}
{{- end }}
