{{- if .Values.oauthProxy.cookieSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babylonCatalog.oauthProxyCookieSecretName" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
data:
  cookieSecret: {{ .Values.oauthProxy.cookieSecret | b64enc }}
{{- end }}
