{{- $admin := .Values.admin }}
{{- if $admin.db.deploy }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $admin.db.secretName }}
  namespace: {{ $admin.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
data:
  hostname: {{ required "$admin.db.hostname is required!" $admin.db.hostname | b64enc }}
  username: {{ required "$admin.db.username is required!" $admin.db.username | b64enc }}
  password: {{ required "$admin.db.password is required!" $admin.db.password | b64enc }}
  name: {{ required "$admin.db.name is required!" $admin.db.name | b64enc }}
{{- else if $admin.db.bitwardenSecret }}
---
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ $admin.db.secretName }}
  namespace: {{ $admin.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  data:
    hostname:
      secret: {{ $admin.db.bitwardenSecret }}
      key: hostname
    name:
      secret: {{ $admin.db.bitwardenSecret }}
      key: name
    password:
      secret: {{ $admin.db.bitwardenSecret }}
      key: password
    port:
      secret: {{ $admin.db.bitwardenSecret }}
      key: port
    username:
      secret: {{ $admin.db.bitwardenSecret }}
      key: username
{{- end -}}
