{{- $admin := .Values.admin }}
{{- if $admin.db.deploy }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $admin.db.secretName }}
  namespace: {{ $admin.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
data:
  hostname: {{ required "$admin.db.hostname is required!" $admin.db.hostname | b64enc }}
  username: {{ required "$admin.db.username is required!" $admin.db.username | b64enc }}
  password: {{ required "$admin.db.password is required!" $admin.db.password | b64enc }}
  name: {{ required "$admin.db.name is required!" $admin.db.name | b64enc }}
{{- end -}}
