{{- $admin := .Values.admin }}
{{- if and $admin.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: babylon-admin
  namespace: {{ $admin.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
{{- end }}