{{- $admin := .Values.admin }}
{{- if $admin.servicenow.deploy }}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ $admin.servicenow.secretName | default "babylon-admin-servicenow" }}
  namespace: {{ $admin.namespace.name }}
spec:
  data:
    authKey: 
      secret: service_now
      key: auth_key
    workshopFormId: 
      secret: service_now
      key: workshop_form_id
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $admin.servicenow.secretName | default "babylon-admin-servicenow" }}
  namespace: {{ $admin.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
data:
  authKey: {{ required "$admin.servicenow.authKey is required!" $admin.servicenow.authKey | b64enc }}
  workshopFormId: {{ required "$admin.servicenow.workshopFormId is required!" $admin.servicenow.workshopFormId | b64enc }}
{{- end }}