---
include:
  - project: enterprise-pipelines/gitlab-ci/includes
    file: SAST/sonarqube.yml

stages:
  - static-analysis

sonarqube:
  variables:
    SONAR_PROJECT_KEY: "com.redhat.rhpds.redhat-cop.babylon"
  tags:
    - itup-alm-x86
