{{- range $namespace, $interface := .Values.catalog.interfaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "babylon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: catalog-api
  name: babylon-catalog-api
  namespace: {{ $namespace }}
{{- end }}
