{{- range $namespace, $interface := .Values.catalog.interfaces }}
---
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: sandbox-api-shared-cluster-manager
  namespace: {{ $namespace }}
spec:
  data:
    shared-cluster-manager-token:
      secret: sandbox_api_shared-cluster-manager_login_token
{{- end }}
