{{ if .Values.awsSandboxManagerCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babylon-cost-tracker.awsSandboxManagerSecretName" . }}
  namespace: {{ include "babylon-cost-tracker.namespaceName" . }}
  labels:
    {{- include "babylon-cost-tracker.labels" . | nindent 4 }}
data:
  aws_access_key_id: {{ .Values.awsSandboxManagerCredentials.awsAccessKeyId | b64enc }}
  aws_secret_access_key: {{ .Values.awsSandboxManagerCredentials.awsSecretAccessKey | b64enc }}
{{ end }}
