apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "babylon-cost-tracker.name" . }}
  annotations:
    description: >-
      Access read cluster resources for babylon cost-tracker
  labels:
    {{- include "babylon-cost-tracker.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kopf.dev
  resources:
  - clusterkopfpeerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.poolboy.domain }}
  resources:
  - resourceclaims
  verbs:
  - get
  - list
  - patch
  - update
  - watch

{{ if .Values.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "babylon-cost-tracker.name" . }}
  labels:
    {{- include "babylon-cost-tracker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "babylon-cost-tracker.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "babylon-cost-tracker.serviceAccountName" . }}
  namespace: {{ include "babylon-cost-tracker.namespaceName" . }}
{{ end }}
