{{ if .Values.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "babylon-cost-tracker.serviceAccountName" . }}
  namespace: {{ include "babylon-cost-tracker.namespaceName" . }}
  labels:
    {{- include "babylon-cost-tracker.labels" . | nindent 4 }}
{{ end }}
