{{- range $namespace, $_interface := .Values.catalog.interfaces }}
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: babylon-catalog-redis
  namespace: {{ $namespace }}
spec:
  forceRegenerate: false
  fields:
  - fieldName: database-password
    encoding: base64
    length: "32"
{{- end }}
