---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: anarchy-operator
rules:
- apiGroups:
  - template.openshift.io
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
