---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opentlc-secret-manager
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - babylon-tower
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - babylon-tower
  verbs:
  - get
- apiGroups:
  - anarchy.gpte.redhat.com
  resources:
  - anarchysubjects
  verbs:
  - get
  - list
  - watch
  - patch
