---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opentlc-secret-manager-admin
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - create
