---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "babylonAgnosticVOperator.name" . }}
  labels:
    {{- include "babylonAgnosticVOperator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.anarchy.apiGroup }}
  resources:
  - anarchygovernors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.catalog.apiGroup }}
  resources:
  - catalogitems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.resourceBroker.apiGroup }}
  resources:
  - resourceproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
