{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "babylonAgnosticVOperator.namespaceName" . }}
  labels:
    {{- include "babylonAgnosticVOperator.labels" . | nindent 4 }}
{{- end -}}
