{{- if .Values.deploy -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "babylonAgnosticVOperator.shortName" . }}
  namespace: {{ include "babylonAgnosticVOperator.namespaceName" . }}
  labels:
    {{- include "babylonAgnosticVOperator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "babylonAgnosticVOperator.shortName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "babylonAgnosticVOperator.serviceAccountName" . }}
  namespace: {{ include "babylonAgnosticVOperator.namespaceName" . }}
{{- end -}}
