{{- if and .Values.deploy .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "babylonAgnosticVOperator.serviceAccountName" . }}
  namespace: {{ include "babylonAgnosticVOperator.namespaceName" . }}
  labels:
    {{- include "babylonAgnosticVOperator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
