= Babylon OpenShift GitOps Configuration

== Setup

Create a virtualenv using python3 and activate it

----
~$ virtualenv -p python3 virtualenvs/k8s-config
created virtual environment CPython3.6.8.final.0-64 in 207ms
  creator CPython3Posix(dest=/home/ec2-user/virtualenvs/k8s-config, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/ec2-user/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

~$ . virtualenvs/k8s-config/bin/activate
(k8s-config) ~$
----

An ansible playbook is provided for Installation.

. Use `pip` to install `ansible` and `openshift`:
+
----------------------------------------------
pip install --upgrade ansible openshift
----------------------------------------------

. Install `k8s_config` ansible role:
+
-----------------------------------------------------------------------------------------
ansible-galaxy install git+https://github.com/redhat-cop/k8s_config.git
-----------------------------------------------------------------------------------------

. Create a deploy key SSH key pair for your private babylon repository, with no password.
+
----
ssh-keygen -f ~/.ssh/babylon-private.rsa
----
+
if you need one for the agnosticv repository:
+
----
ssh-keygen -f ~/.ssh/agnosticv-private.rsa
----

. In your Git hosting provider (github, gitlab, ...) add read-only access for
those keys.
For github it's in *Settings / Deploy keys*.
Here is how to get the public key from the private key generated above, add `-y`
to the `ssh-keygen` command:
+
----
ssh-keygen -f ~/.ssh/babylon-private.rsa -y
----
+
----
ssh-keygen -f ~/.ssh/agnosticv-private.rsa -y
----
+
NOTE: The private babylon repository should define the variable `babylon_private_resources` with a list of resources to create such as cluster role bindings.

. Clone this repository and enter the openshift/config directory
+
----
git clone https://github.com/redhat-cop/babylon.git
cd babylon/openshift/config
----

. Run the `setup-playbook.yaml` Ansible playbook from this directory:
+
The k8s_config_environment_level should be set to `dev`, `test`, or `prod`.
If your OpenShift server is not configured with a known TLS certificate authority, set `k8s_api_validate_certs=false`.
+
If you have private configuration sources you may specify `babylon_private_repo` and `babylon_private_deploy_key` to add your private config source.
Your private config source should define `babylon_private_resources` for custom `k8s_config` resources.
If your private config source provides agnosticv-operator configuration you may also need to pass credentials for agnosticv access.
+
.Create and update this `cluster-vars.yml`
----------------------------------------
k8s_config_environment_level: dev
babylon_private_repo_url: git@github.com:redhat-gpe/babylon-private.git
babylon_private_deploy_key: ~/.ssh/babylon-private.rsa
agnosticv_repositories:
    - name: gpte-agnosticv
      url: git@github.com:redhat-gpe/agnosticv.git
      ssh_key: ~/.ssh/agnosticv-private.rsa
----------------------------------------
+
.Then run
----------------------------------------
ansible-playbook setup-playbook.yaml -e @cluster-vars.yml
----------------------------------------

. Create a secret, `babylon-tower`, in the `anarchy-operator` namespace with the user, password, and hostname used to connect to the Anisble dark-tower component.
+
-----
oc create -n anarchy-operator secret generic babylon-tower \
--from-literal=hostname=... \
--from-literal=user=... \
--from-literal=password=...
-----

== Available Variables

* `babylon_repo_url` - Source for main babylon config.
Default: "https://github.com/redhat-cop/babylon.git"

* `babylon_repo_version`: Repository version (tag or branch) for main babylon config.
Default: "master"

* `babylon_private_repo_url`: Private babylon configuration repository URL.
Optional, no private repository by default.

* `babylon_private_repo_version`: Private babylon configuration repository version.
Default: "master"

* `babylon_private_deploy_key`: Path to SSH key used to access private config repository.
