= Babylon OpenShift GitOps Configuration

== Setup

An ansible playbook is provided for Installation.

. Use `pip` to install `ansible` and `openshift`:
+
----------------------------------------------
pip install --upgrade --user ansible openshift
----------------------------------------------

. Install `k8s_config` ansible role:
+
-----------------------------------------------------------------------------------------
ansible-galaxy install git+https://github.com/redhat-cop/k8s_config.git
-----------------------------------------------------------------------------------------

. Create a deploy key SSH key pair for your private babylon repository.
+
The private repository should define the variable `babylon_private_resources` with a list of resources to create such as cluster role bindings.

. Run the `setup-playbook.yaml` Ansible playbook from this directory:
+
The k8s_config_environment_level should be set to `dev`, `test`, or `prod`.
If your OpenShift server is not configured with a known TLS certificate authority, set `k8s_api_validate_certs=false`.
+
If you have private configuration sources you may specify `babylon_private_repo` and `babylon_private_deploy_key` to add your private config source.
Your private config source should define `babylon_private_resources` for custom `k8s_config` resources.
If your private config source provides agnosticv-operator configuration you may also need to pass credentials for agnosticv access.
+
----------------------------------------
ansible-playbook setup-playbook.yaml \
-e '{
  "k8s_config_environment_level": "dev",
  "babylon_private_repo_url": "git@github.com:redhat-gpe/babylon-private.git",
  "babylon_private_deploy_key": "~/.ssh/babylon-private.rsa",
  "agnosticv_repositories": [{
    "name": "gpte-agnosticv",
    "url": "git@github.com:redhat-gpe/agnosticv.git",
    "ssh_key": "~/.ssh/agnosticv-private.rsa"
  }]
}'
----------------------------------------

. Create a secret, `babylon-tower`, in the `anarchy-operator` namespace with the user, password, and hostname used to connect to the Anisble dark-tower component.
+
-----
oc create secret generic babylon-tower \
--from-literal=hostname=... \
--from-literal=user=... \
--from-literal=password=...
-----

== Available Variables

* `babylon_repo_url` - Source for main babylon config.
Default: "https://github.com/redhat-cop/babylon.git"

* `babylon_repo_version`: Repository version (tag or branch) for main babylon config.
Default: "master"

* `babylon_private_repo_url`: Private babylon configuration repository URL.
Optional, no private repository by default.

* `babylon_private_repo_version`: Private babylon configuration repository version.
Default: "master"

* `babylon_private_deploy_key`: Path to SSH key used to access private config repository.
