apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workshops.babylon.gpte.redhat.com
spec:
  conversion:
    strategy: None
  group: babylon.gpte.redhat.com
  names:
    kind: Workshop
    listKind: WorkshopList
    plural: workshops
    singular: workshop
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: >-
          Workshop definition which provides a user interface for unauthenticated users to access workshop services.
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*[a-z0-9A-Z])?$
                type: string
            type: object
          spec:
            description: Specification of Workshop.
            type: object
            properties:
              accessPassword:
                description: >-
                  Optional password for access to the workshop.
                type: string
              actionSchedule:
                description: >-
                  Configuration for when services should start and stop to propagate to WorkshopProvisions that belong to this Workshop.
                  This configuration is only for Workshops that have WorkshopProvisions.
                  This configuration has no effect for Workshops that are owned by a ResourceClaim.
                type: object
                properties:
                  start:
                    description: >-
                      Time when services should start. If in the future then services should be stopped.
                    type: string
                    format: date-time
                  stop:
                    description: >-
                      Time when services should stop. If in the past then services should be stopped.
                    type: string
                    format: date-time
              description:
                description: >-
                  Description text for the workshop.
                type: string
              displayName:
                description: >-
                  Display name for the workshop.
                type: string
              labUserInterface:
                description: >-
                  Default settings for labUserInterface under userAssignments.
                type: object
                properties:
                  redirect:
                    description: >-
                      Configure that users should be automatically redirected to the lab user interface.
                    type: boolean
              lifespan:
                description: >-
                  Lifespan settings for this Workshop.
                  This configuration is meant for Workshops that have WorkshopProvisions.
                  Lifespan for Workshops owned by a ResourceClaim should be managed through the owning ResourceClaim.
                type: object
                properties:
                  end:
                    description: >-
                      End of lifespan for Workshop any WorkshopProvisions that belong to it.
                    type: string
                    format: date-time
                  start:
                    description: >-
                      Start of lifespan for Workshop any WorkshopProvisions that belong to it.
                    type: string
                    format: date-time
              multiuserServices:
                description: >-
                  Flag to indicate that services for this workshop are multi-user.
                type: boolean
              openRegistration:
                description: >-
                  If set to true then users will not need to be pre-registered.
                type: boolean
              provisionDisabled:
                description: >-
                  If set then WorkshopProvisions are disabled for this Workshop.
                  This is appropriate to set when a multi-user workshop environment is provisioned first and then a Workshop is created later to provide access only.
                  In this case the Workshop should also be set to be owned by the ResourceClaim for the service.
                type: boolean
              userAssignments:
                description: >-
                  Users for multi-user workshop environments.
                type: array
                items:
                  type: object
                  properties:
                    assignment:
                      description: >-
                        Assignment for workshop participant.
                      type: object
                      required:
                      - email
                      properties:
                        email:
                          description: >-
                            Email address used to identify workshop participant.
                          type: string
                    data:
                      description: >-
                        Any data items reported for the user from the service provisioning.
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    labUserInterface:
                      description: >-
                        Lab user interface information for user access.
                      type: object
                      properties:
                        redirect:
                          description: >-
                            Configure that users should be automatically redirected to the lab user interface.
                          type: boolean
                        url:
                          description: >-
                            URL for the lab user interface.
                          type: string
                    messages:
                      description: >-
                        Any messages reported for the user from the service provisioning.
                      type: string
                    resourceClaimName:
                      description: >-
                        ResourceClaim name.
                      type: string
                    userName:
                      description: >-
                        User name for lab as reported from the service provisioning.
                      type: string
          status:
            description: Status of Workshop
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
