---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: babylon:{{ .Values.resourceBroker.namespace }}:anarchy-access
  annotations:
    description: >-
      This rolebinding allows the resource broker to manage anarchy resources.
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: babylon:{{ .Values.resourceBroker.serviceAccountName }}:anarchy-access
subjects:
- kind: ServiceAccount
  name: {{ .Values.resourceBroker.serviceAccountName }}
  namespace: {{ .Values.resourceBroker.namespace }}
