# Babylon Workshop Provisioner

Development can be performed in the `odo` OpenShift developer CLI or building with OpenShift build configs.
An OpenShift cluster with cluster-admin is required for `odo` development.
https://developers.redhat.com/products/codeready-containers/overview[CodeReady Containers] is recommended for local development.
An Ansible test suite is available for functional testing.

## Development with `odo`

Use of `odo` is recommended for fast iterative development.
`odo` simplifies the build/deploy process and avoids creating unnecessary build artifacts during the development process.

Install the `odo` developer CLI as described in the OpenShift documentation:
https://docs.openshift.com/container-platform/latest/cli_reference/developer_cli_odo/installing-odo.html[Installing odo]

### Replace current deployment

The most simple way is to downscale the current deployment and replace it with a development version using `odo`. This
is useful since not requiring any additional resources (ClusterRole, ServiceAccount, etc.) and allows you to
quickly iterate on the code.

. Downscale the current deployment to 0 replicas:
+
---------------------------------------------------
oc scale deploy babylon-workshop-manager --replicas=0
---------------------------------------------------

. Run `odo` in the current project (the path where the `devfile.yaml` is located):
+
---------------------------------------------------
odo dev
---------------------------------------------------

. Cleanup. Upscale the current deployment back to 1 replica:
+---------------------------------------------------
oc scale deploy babylon-workshop-manager --replicas=1
+---------------------------------------------------

### Create a new development project
This is useful if you want to keep the current deployment running while you develop a new version of the babylon-workshop-manager.

#### Setup

. Create a project for development using `odo`:
+
---------------------------------------------------
oc new-project babylon-workshop-manager-dev
---------------------------------------------------

. Create Babylon workshop-manager resources from the provided helm chart:
+
-----------------------------------------------------
helm template helm \
--set deploy=false \
--set nameOverride=babylon-workshop-manager-dev \
--set namespace.name=$(oc project --short) \
| oc apply -f -
-----------------------------------------------------

. Grant privileges for cluster role `babylon-workshop-manager-dev` to default service account:
+
----------------------------------------------------------------------------------
oc adm policy add-cluster-role-to-user babylon-workshop-manager-dev -z default
----------------------------------------------------------------------------------

. Setup `odo` from the provided `devfile.yaml`:
+
---------------------------------
odo dev
---------------------------------

[TIP]
====
Most likely required ClusterRole (e.g. `babylon-workshop-manager`) is already created
by the existing deployment. In this case, you can skip the `helm template` step and just
add the ClusterRole to the `default` service account.
---------------------------------------------------
oc adm policy add-cluster-role-to-user babylon-workshop-manager -z default
---------------------------------------------------
====

#### Cleanup

. Remove the `babylon-workshop-manager-dev` cluster role binding
+
--------------------------------------------------------------------------------
oc adm policy remove-cluster-role-from-user babylon-workshop-manager-dev -z default
--------------------------------------------------------------------------------
+
. Remove resources created from the helm template
+
-----------------------------------------------------
helm template helm \
--set deploy=false \
--set nameOverride=babylon-workshop-manager-dev \
--set namespace.name=$(oc project --short) \
| oc delete -f -
-----------------------------------------------------

## Development OpenShift Build

The OpenShift build process is a bit slower for development but has the advantage of being a bit closer to a normal deployment of the babylon-workshop-manager.
It is often best to iterate development using `odo` and also test with an OpenShift build and deployment prior to opening a pull request.

. Create a project for development using `oc`:
+
-----------------------------------------------
oc new-project babylon-workshop-manager-dev
-----------------------------------------------

. Process OpenShift build template to create BuildConfig and ImageStream:
+
---------------------------------------------------------
oc process --local -f build-template.yaml | oc apply -f -
---------------------------------------------------------

. Build babylon-workshop-manager image from local source:
+
------------------------------------------------------------------
oc start-build babylon-workshop-manager --from-dir=.. --follow
------------------------------------------------------------------

. Deploy babylon-workshop-manager from build image
+
--------------------------------------------------------------------------------
helm template helm \
--set nameOverride=babylon-workshop-manager-dev \
--set namespace.create=false \
--set=image.override="$(oc get imagestream babylon-workshop-manager -o jsonpath='{.status.tags[?(@.tag=="latest")].items[0].dockerImageReference}')" \
| oc apply -f -
--------------------------------------------------------------------------------

. Cleanup
+
Remove resources created from the helm template:
+
-----------------------------------------------------
helm template helm \
--set nameOverride=babylon-workshop-manager-dev \
--set namespace.create=false \
| oc delete -f -
-----------------------------------------------------
+
Remove BuildConfig and ImageStream:
+
----------------------------------------------------------
oc process --local -f build-template.yaml | oc delete -f -
----------------------------------------------------------
