# Babylon Workshop Provisioner

## Local development

### Replace current deployment

The most simple way is to downscale the current deployment and replace it with a development version using `odo`. This
is useful since not requiring any additional resources (ClusterRole, ServiceAccount, etc.) and allows you to
quickly iterate on the code.

. Downscale the current deployment to 0 replicas:
+
---------------------------------------------------
oc scale deployment/babylon-workshop-manager -n babylon-workshop-manager --replicas=0
---------------------------------------------------

. Run local with provided shell script:
+
---------------------------------------------------
./run-local.sh
---------------------------------------------------

## Development OpenShift Build

The OpenShift build process is a bit slower for development but has the advantage of being a bit closer to a normal deployment of the babylon-workshop-manager.
It is often best to iterate development using `odo` and also test with an OpenShift build and deployment prior to opening a pull request.

. Switch to `babylon-workshop-manager` project:
+
-----------------------------------
oc project babylon-workshop-manager
-----------------------------------

. Process OpenShift build template to create BuildConfig and ImageStream:
+
---------------------------------------------------------
oc process --local -f build-template.yaml | oc apply -f -
---------------------------------------------------------

. Build babylon-workshop-manager image from local source:
+
--------------------------------------------------------------
oc start-build babylon-workshop-manager --from-dir=.. --follow
--------------------------------------------------------------

. Update deployment `babylon-workshop-manager` to use new image:
+
----
oc patch deployment babylon-workshop-manager --type=json -p '[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"'$(oc get imagestream babylon-workshop-manager -o jsonpath='{.status.tags[?(@.tag=="latest")].items[0].dockerImageReference}')'"}]'
----
