apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "babylon-workshop-manager.name" . }}
  annotations:
    description: >-
      Access read cluster resources for babylon workshop-manager
  labels:
    {{- include "babylon-workshop-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kopf.dev
  resources:
  - clusterkopfpeerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.babylon.domain }}
  resources:
  - catalogitems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ .Values.babylon.domain }}
  resources:
  - workshops
  - workshops/status
  - workshopprovisions
  - workshopprovisions/status
  - workshopuserassignments
  - workshoppuserassignments/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.poolboy.domain }}
  resources:
  - resourceclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.poolboy.domain }}
  resources:
  - resourcehandles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
{{ if .Values.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "babylon-workshop-manager.name" . }}
  labels:
    {{- include "babylon-workshop-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "babylon-workshop-manager.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "babylon-workshop-manager.serviceAccountName" . }}
  namespace: {{ include "babylon-workshop-manager.namespaceName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "babylon-workshop-manager.name" . }}:admin
  labels:
    {{- include "babylon-workshop-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ include "babylon-workshop-manager.serviceAccountName" . }}
  namespace: {{ include "babylon-workshop-manager.namespaceName" . }}
{{ end }}
