{{ if .Values.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "babylon-workshop-manager.serviceAccountName" . }}
  namespace: {{ include "babylon-workshop-manager.namespaceName" . }}
  labels:
    {{- include "babylon-workshop-manager.labels" . | nindent 4 }}
{{ end }}
