{{- $notifier := .Values.notifier }}
{{- if and $notifier.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-notifier-anarchy-access
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifier
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ .Values.anarchy.domain }}
  resources:
  - anarchyactions
  - anarchygovernors
  - anarchyruns
  - anarchysubjects
  verbs:
  - get
  - list
  - watch
{{- range $namespace := $.Values.anarchy.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: babylon-notifier
  namespace: {{ $namespace.name }}
  labels:
    {{- include "babylon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: notifier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: babylon-notifier-anarchy-access
subjects:
- kind: ServiceAccount
  name: babylon-notifier
  namespace: {{ $notifier.namespace.name }}
{{- end }}
{{- end }}
