{{- if and .Values.notifier.deploy .Values.notifier.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "babylon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: notifier
  name: {{ .Values.notifier.namespace.name }}
{{- end }}
