{{- $notifier := .Values.notifier }}
{{- if and $notifier.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: babylon-notifier
  namespace: {{ $notifier.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifier
{{- end }}
