{{- if .Values.jira.deploy }}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .Values.jira.secretName | default "babylon-catalog-jira" }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
spec:
  data:
    jira-api-token:
      secret: jira_credentials
      key: api_token
    jira-user-email:
      secret: jira_credentials
      key: user_email
    jira-base-url:
      secret: jira_credentials
      key: base_url
    jira-project-key:
      secret: jira_credentials
      key: project_key
{{- end }}
