{{- if .Values.salesforce }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babylonCatalog.apiName" . }}-salesforce
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
type: Opaque
data:
  consumer_key: {{ .Values.salesforce.consumer_key | b64enc }}
  instance: {{ .Values.salesforce.instance | b64enc }}
  privatekey: {{ .Values.salesforce.privatekey | b64enc }}
  username: {{ .Values.salesforce.username | b64enc }}
{{- end }}
