{{- if .Values.sandboxApi.deploy }}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .Values.sandboxApi.secretName | default "babylon-catalog-sandbox-api" }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
spec:
  data:
    sandbox-api-token: 
      secret: sandbox_api_login_token_catalog
{{- end }}