{{- if .Values.sharedClusterManager.deploy }}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .Values.sharedClusterManager.secretName | default "sandbox-api-shared-cluster-manager" }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
spec:
  data:
    shared-cluster-manager-token:
      secret: sandbox_api_shared-cluster-manager_login_token
{{- end }}
