apiVersion: v1
kind: Service
metadata:
  name: {{ include "babylonCatalog.statusName" . }}
  namespace: {{ include "babylonCatalog.namespaceName" . }}
  labels:
    {{- include "babylonCatalog.labels" . | nindent 4 }}
spec:
  ports:
  - name: proxy
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "babylonCatalog.statusSelectorLabels" . | nindent 4 }}
  type: ClusterIP
