{{- range $namespace, $_interface := .Values.catalog.interfaces }}
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: babylon-catalog-oauth-proxy-cookie
  namespace: {{ $namespace }}
spec:
  forceRegenerate: false
  fields:
  - fieldName: cookieSecret
    encoding: base64
    length: "32"
{{- end }}
