{{- $notifier := .Values.notifier }}
{{- if $notifier.deploy }}
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: babylon-notifier-redis
  namespace: {{ $notifier.namespace.name }}
spec:
  forceRegenerate: false
  fields:
  - fieldName: database-password
    encoding: base64
    length: "32"
{{- end }}
