{{- $tenantClusterPoolManager := .Values.tenantClusterPoolManager }}
{{- if and $tenantClusterPoolManager.deploy $tenantClusterPoolManager.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "babylon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: tenant-cluster-pool-manager
  name: {{ $tenantClusterPoolManager.namespace.name }}
{{- end }}
