{{- $tenantClusterPoolManager := .Values.tenantClusterPoolManager }}
{{ if $tenantClusterPoolManager.deploy }}
---
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: sandbox-api
  namespace: {{ $tenantClusterPoolManager.namespace.name }}
spec:
  data:
    token:
      secret: sandbox_api_login_token_catalog
{{ end }}
