{{- $tenantClusterPoolManager := .Values.tenantClusterPoolManager }}
{{- if and $tenantClusterPoolManager.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: babylon-tenant-cluster-pool-manager
  namespace: {{ $tenantClusterPoolManager.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: tenant-cluster-pool-manager
{{- end }}
