version: 1
disable_existing_loggers: False
formatters:
  timestamped:
    format: '%(asctime)s - %(levelname)s - %(message)s'
  json:
    (): json_formatter.JSONFormatter
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]
