version: 1
disable_existing_loggers: False
formatters:
  timestamped:
    format: '%(asctime)s - %(levelname)s - %(message)s'
#formatters:
#  simple:
#    format: '%(asctime)s:%(levelname)s: %(name)s - %(message)s'
#handlers:
#  console:
#    class: logging.StreamHandler
#    level: INFO
#    formatter: simple
#    stream: ext://sys.stdout
#loggers:
#  consoleLogger:
#    level: INFO
#    handlers: [console]
#    propagate: no
#root:
#  level: INFO
#  handlers: [console]
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: timestamped
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]