{{ if .Values.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "babylon-ratings.serviceAccountName" . }}
  namespace: {{ include "babylon-ratings.namespaceName" . }}
  labels:
    {{- include "babylon-ratings.labels" . | nindent 4 }}
{{ end }}
