
apiVersion: v1
kind: Service
metadata:
  name: {{ include "babylon-ratings.name" . }}
  namespace: {{ include "babylon-ratings.namespaceName" . }}
  labels:
    {{- include "babylon-ratings.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: ratings-api
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "babylon-ratings.selectorLabels" . | nindent 4 }}