apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalog-read-agnosticvcomponent-rolebinding
  namespace: {{ .Values.configNamespace.name }}
  labels:
    {{- include "babylon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: agnosticv-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: catalog-read-agnosticvcomponent-role
subjects:
{{- range $namespace, $interface := .Values.catalog.interfaces }}
- kind: ServiceAccount
  name: babylon-catalog-api
  namespace: {{ $namespace }}
{{- end }}
