---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: babylon-agnosticv-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: babylon-agnosticv-operator
subjects:
- kind: ServiceAccount
  name: agnosticv-operator
  namespace: {{ .Values.configNamespace.name }}
