---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agnosticv-operator
  namespace: {{ .Values.configNamespace.name }}
  labels:
    {{- include "babylon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: agnosticv-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agnosticv-operator
subjects:
- kind: ServiceAccount
  name: agnosticv-operator
  namespace: {{ .Values.configNamespace.name }}
