---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agnosticv-operator
  namespace: {{ .Values.configNamespace.name }}
  labels:
    {{- include "babylon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: agnosticv-operator
