{{- $selfpacedlabManager := .Values.selfpacedlabManager }}
{{- if and $selfpacedlabManager.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: babylon-selfpacedlab-manager
  namespace: {{ $selfpacedlabManager.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: selfpacedlab-manager
{{- end }}
