{{- if .Values.db.deploy }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "babylon-admin.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
data:
  hostname: {{ required "Values.db.hostname is required!" .Values.db.hostname | b64enc }}
  username: {{ required "Values.db.username is required!" .Values.db.username | b64enc }}
  password: {{ required "Values.db.password is required!" .Values.db.password | b64enc }}
  name: {{ required "Values.db.name is required!" .Values.db.name | b64enc }}
{{- else if .Values.db.bitwardenSecret }}
---
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .Values.db.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "babylon-admin.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  data:
    hostname:
      secret: {{ .Values.db.bitwardenSecret }}
      key: hostname
    name:
      secret: {{ .Values.db.bitwardenSecret }}
      key: name
    password:
      secret: {{ .Values.db.bitwardenSecret }}
      key: password
    port:
      secret: {{ .Values.db.bitwardenSecret }}
      key: port
    username:
      secret: {{ .Values.db.bitwardenSecret }}
      key: username
{{- end -}}
