{{- if .Values.db.deploy -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  namespace: {{ include "babylon-admin.namespaceName" . }}
  labels:
    {{- include "babylon-admin.labels" . | nindent 4 }}
data:
  hostname: {{ required ".Values.db.hostname is required!" .Values.db.hostname | b64enc }}
  username: {{ required ".Values.db.username is required!" .Values.db.username | b64enc }}
  password: {{ required ".Values.db.password is required!" .Values.db.password | b64enc }}
  name: {{ required ".Values.db.name is required!" .Values.db.name | b64enc }}
{{- end -}}
