apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "babylon-admin.name" . }}
  annotations:
    description: >-
      Access read cluster resources for babylon admin
  labels:
    {{- include "babylon-admin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kopf.dev
  resources:
  - clusterkopfpeerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{ if .Values.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "babylon-admin.name" . }}
  labels:
    {{- include "babylon-admin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "babylon-admin.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "babylon-admin.serviceAccountName" . }}
  namespace: {{ include "babylon-admin.namespaceName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "babylon-admin.name" . }}:admin
  labels:
    {{- include "babylon-admin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ include "babylon-admin.serviceAccountName" . }}
  namespace: {{ include "babylon-admin.namespaceName" . }}
{{ end }}
