{{- if .Values.servicenow.deploy }}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .Values.servicenow.secretName | default "babylon-admin-servicenow" }}
  namespace: {{ include "babylon-admin.namespaceName" . }}
spec:
  data:
    authKey: 
      secret: service_now
      key: auth_key
    workshopFormId: 
      secret: service_now
      key: workshop_form_id
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.servicenow.secretName | default "babylon-admin-servicenow" }}
  namespace: {{ include "babylon-admin.namespaceName" . }}
  labels:
    {{- include "babylon-admin.labels" . | nindent 4 }}
data:
  authKey: {{ required ".Values.servicenow.authKey is required!" .Values.servicenow.authKey | b64enc }}
  workshopFormId: {{ required ".Values.servicenow.workshopFormId is required!" .Values.servicenow.workshopFormId | b64enc }}
{{- end }}
