{{ if .Values.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "babylon-admin.serviceAccountName" . }}
  namespace: {{ include "babylon-admin.namespaceName" . }}
  labels:
    {{- include "babylon-admin.labels" . | nindent 4 }}
{{ end }}
