{{- if .Values.snow.deploy -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.snow.secretName }}
  namespace: {{ include "babylon-admin.namespaceName" . }}
  labels:
    {{- include "babylon-admin.labels" . | nindent 4 }}
data:
  authKey: {{ required ".Values.snow.authKey is required!" .Values.snow.authKey | b64enc }}
  formId: {{ required ".Values.snow.formId is required!" .Values.snow.formId | b64enc }}
{{- end -}}
