{{- if .Values.snow.deploy }}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .Values.snow.secretName | default "babylon-admin-snow-credentials" }}
  namespace: {{ include "babylon-admin.namespaceName" . }}
spec:
  data:
    authKey: 
      secret: service_now_auth_key
    workshopFormId: 
      value: service_now_workshop_form_id
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.snow.secretName | default "babylon-admin-snow-credentials" }}
  namespace: {{ include "babylon-admin.namespaceName" . }}
  labels:
    {{- include "babylon-admin.labels" . | nindent 4 }}
data:
  authKey: {{ required ".Values.snow.authKey is required!" .Values.snow.authKey | b64enc }}
  workshopFormId: {{ required ".Values.snow.workshopFormId is required!" .Values.snow.workshopFormId | b64enc }}
{{- end }}
