apiVersion: v1
kind: Service
metadata:
  name: {{ include "babylon-notifier.redisName" . }}
  namespace: {{ include "babylon-notifier.namespaceName" . }}
  labels:
    {{- include "babylon-notifier.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    {{- include "babylon-notifier.redisSelectorLabels" . | nindent 4 }}
