apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentlc-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentlc-deployer
subjects:
- kind: ServiceAccount
  name: opentlc-mgr
  namespace: gpte
