{{- $catalogManager := .Values.catalogManager }}
{{- if $catalogManager.db.deploy }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $catalogManager.db.secretName | default "gpte-db-secrets" }}
  namespace: {{ $catalogManager.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalog-manager
data:
  hostname: {{ required ".Values.catalogManager.db.hostname is required!" $catalogManager.db.hostname | b64enc }}
  username: {{ required ".Values.catalogManager.db.username is required!" $catalogManager.db.username | b64enc }}
  password: {{ required ".Values.catalogManager.db.password is required!" $catalogManager.db.password | b64enc }}
  dbname: {{ required ".Values.catalogManager.db.name is required!" $catalogManager.db.name | b64enc }}
  port: {{ required ".Values.catalogManager.db.port is required!" $catalogManager.db.port | b64enc }}
{{- else if $catalogManager.db.bitwardenSecret }}
---
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ $catalogManager.db.secretName | default "gpte-db-secrets" }}
  namespace: {{ $catalogManager.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalog-manager
spec:
  data:
    hostname:
      secret: {{ $catalogManager.db.bitwardenSecret }}
      key: hostname
    username:
      secret: {{ $catalogManager.db.bitwardenSecret }}
      key: username
    password:
      secret: {{ $catalogManager.db.bitwardenSecret }}
      key: password
    dbname:
      secret: {{ $catalogManager.db.bitwardenSecret }}
      key: dbname
    port:
      secret: {{ $catalogManager.db.bitwardenSecret }}
      key: port
{{- end }}
