---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon:anarchy:{{ .Values.resourceBroker.serviceAccountName }}-access
  annotations:
    description: >-
      This cluster role is used to allow anarchy to manage ResourceClaims and ResourceHandles.
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: anarchy
rules:
- apiGroups:
  - {{ .Values.resourceBroker.api.group }}
  resources:
  - resourceclaims
  - resourcehandles
  verbs:
  - delete
  - get
  - list
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon:anarchy:anarchy-namespace-access
  annotations:
    description: >-
      This cluster role controls the anarchy runner service account access to its own namespace.
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
