deploy: true
replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

namespace:
  create: true
  name:

serviceAccount:
  create: true
  annotations: {}
  name:

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

babylon:
  domain: babylon.gpte.redhat.com

selfpacedlabBaseUrl: ""

poolboy:
  domain: poolboy.gpte.redhat.com

image:
  repository: quay.io/rhpds/babylon-selfpacedlab-manager
  pullPolicy: Always
  tagOverride: ""
