{{ if .Values.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "babylon-ratings.name" . }}
  namespace: {{ include "babylon-ratings.namespaceName" . }}
  labels:
    {{- include "babylon-ratings.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "babylon-ratings.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "babylon-ratings.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: ratings-api
        env:
        - name: RATINGS_COMPONENT
          value: api
        - name: TZ
          value: 'UTC'
        - name: DB_MAX_OVERFLOW
          value: {{ default "40" .Values.db.maxOverflow |quote }}
        - name: DB_POOL_SIZE
          value: {{ default "10" .Values.db.poolSize |quote }}
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              key: hostname
              name:  {{ default .Values.db.secretName "database" }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name:  {{ default .Values.db.secretName "database" }}
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: name
              name: {{ default .Values.db.secretName "database" }}
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ default .Values.db.secretName "database" }}
        - name: DB_PORT
          value: {{ default .Values.db.port "54327" |quote }}
        image: {{ include "babylon-ratings.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "babylon-ratings.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
