---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: OPENTLC deployer
  name: opentlc-deployer
rules:
- apiGroups:
  - ""
  - project.openshift.io
  resources:
  - projectrequests
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/status
  verbs:
  - list
  - get
  - watch
  - create
  - patch
- apiGroups:
  - poolboy.gpte.redhat.com
  resources:
  - resourceclaims
  - resourcehandles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
