:toc2:

= Dark Tower API Interface

This document describes the optional and mandatory variables expected by Dark Tower's `job-runner` job template.

NOTE: This document assumes basic familiarity with Ansible Tower and concepts such as Job Templates, Projects etc. 

== Overview

Dark Tower's `job-runner` expects to be called with a JSON payload consisting of at least one, and optionally two, dictionaries:

* `job_vars`
* `secrets`

The entire variable payload can be passed in the `job_vars` dictionary but by using a second dictionary `secrets` a more secure separation of variable can be observed and allow for simpler sharing of the non confidential, and often organization specific, credentials etc.

.Sample "all-in-one" vars file
[source,yaml]
----
job_vars:                                                 <1>
  __meta__:                                               <2> 
    deployer:                                             <3>             
      scm_type:                 git
      scm_url:                  https://github.com/redhat-cop/agnosticd.git
      scm_ref:                  three-tier-app-prod-1.14
      scm_tag_prefix:           three-tier-app-prod  # Dynamic lookup of latest tag
      type:                     agnosticd # default agnosticd
      entry_point:              ansible/main.yml

    callback:                                             <4>
      url:                      ``
      token:                    `` 

    tower:                                                <5>
      organization:             gpte
      run_group:                emea  # e.g.region hint, stage hint (dev|prod)
      action:                   deploy 
                                                          <6>
  guid:                         baby-three-01
  env_type:                     three-tier-app
  email:                        babylon@example.com
  subdomain_base_suffix:        .example.opentlc.com
  own_repo_path:                http://admin.example.com/repos/
  cloud_provider:               ec2
  aws_region:                   us-east-1
  aws_hosted_zone_id:           Z3IHLWJZOU9SRT
  key_name:                     ocpkey
  aws_access_key_id:            YOUR-KEY-HERE            
  aws_secret_access_key:        YOUR-SECRET-KEY-HERE
  ...
----

. `job_vars` top level dictionary
. `__meta__` metadata not required to be passed to `agnosticd`
. `deployer` metadata used by Dark Tower to create necessary Tower constructs
. `callback` optional callback data to allow Dark Tower to call back to Anarchy for example
. `tower` metadata specific to Tower internal structures and schduling
/
...
''''


[cols="8%,8%,8%,25%,25%,10%]
|=============================================
| Parent | | | | Purpose | Example | Mandatory

| `job_vars`
| 
|
|
| Top Level Dictionary
| *NA*
| Yes

|
| `__meta__`
|
|
| Metadata for Dark Tower
| *NA*
| Yes

|
|
| `deployer`
|
| Metadata for Ansible Based deployer repo e.g. AgnosticD
| *NA*
| Yes


|
|
| 
| `scm_type`                 
| Type of SCM system
| `git`
| No


|
|
| 
| `scm_url`
| URL of SCM
| https://github.com/redhat-cop/agnosticd.git
| Yes


|
|
| 
| `scm_ref`
| git tag *or* branch to check out
| `three-tier-app-prod-1.14`
| No


|
|
| 
| `scm_tag_prefix`
| git tag prefix to perform lookup of latest version and check out
| `three-tier-app-prod`
| No


|
|
| 
| `type`
| Name of deployer
| `agnosticd`
| Yes


|=============================================


      type:                     agnosticd # default agnosticd
      entry_point:              ansible/main.yml






 `guid`
| String
| Mandatory
| Global Unique Identifier
| 1234

| `babylon_dark_tower_organization`
| String
| Mandatory
| Assign to Tower organization
| gpte

| `babylon_dark_tower_run_group`
| String
| us
| Hint to Dark Tower for schdeuling locality
| `emea` or `prod` 

| `babylon_deployer_scm_type`
| String
| `git`
| Type of SCM for Dark Tower project
| `git`

| `babylon_deployer_scm_url`           
| URL
| Mandatory
| Location of deployer repo
| https://github.com/redhat-cop/agnosticd.git

| `babylon_deployer_scm_ref`
| String
| `development`
| branch, commit, or tag to check out in job project
| `three-tier-app-prod-1.14`

| `babylon_deployer_scm_tag_prefix`
| String
| Optional
| Dark Tower will look up the highest release tag of that prefix | 
`three-tier-app-prod` footnote:[Mutually exclusive with `babylon_deployer_ref` *WARNING* abbreviated prefixes may lead to undesired effects e.g. `three-tier-app` would fetch the highest test tag and *not* rpoduction.]


| `babylon_deployer_type`
| String
| `agnosticd`
| Create maningfully named tower objects and log output
| `agnosticd`

| `babylon_deployer_action`            deploy 
| String
| deploy
| Log output and hints to dark tower as to type of workload
| `deploy|stop|start|destroy` etc.,

| `babylon_deployer_entry_point`
| String
| Mandatory
| Entry playbook for Dark Tower Job Template
| `ansible/main.yml`

| `babylon_callback_url`
| URL
| Optional
| Callback URL for Dark Tower to communicate Job Status
| http://reciever.openshift.example.com/callback

| `babylon_callback_token`
| Optional
| Callback Token for Dark Tower to communicate Job Status
| EIEp   IO
| `sY45jk7632ooi43oiu`
|=============================================

.Sample Var File for agnosticd link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/configs/three-tier-app[config `three-tier-app`]
[source,yaml]
----

---
guid:                               baby-three-01

babylon_dark_tower_organization:    gpte
babylon_dark_tower_run_group:       emea  # e.g.region hint, stage hint (dev|prod)

babylon_deployer_scm_type:          git
babylon_deployer_scm_url:           https://github.com/redhat-cop/agnosticd.git
babylon_deployer_scm_ref:           three-tier-app-prod-1.14
# babylon_deployer_scm_tag_prefix:    three-tier-app-prod  # Dynamic lookup of latest tag

babylon_deployer_type:              agnosticd # default agnosticd
babylon_deployer_action:            deploy 
babylon_deployer_entry_point:       ansible/main.yml

babylon_callback_url:               ""
babylon_callback_token:             "" 

environment_parameters:

----
