== Deploying a Babylon Dark Tower Cluster

Overview

This document outlines deploying the Dark Tower backend(s) for the Babylon project. So named as they can be deployed and run completely lights out without any manual configuration "lighting up" the Ansible Tower front end.

* Your own Dark Tower test/dev/prod infrastructure
** Single tower server
** Cluster

NOTE: Dark Tower can be deployed on a global scale using peered VPCs on AWS on top of this link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/configs/multi-region-example[AgnosticD configuration]. This is not covered in this document which serves as a Quick Start guide.

A Babylon Dark Tower cluster is an link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/configs/ansible-tower[AgnosticD Config] with the necessary vars outlined below. 

=== Pre-requisites

* A host capable and configured for running Ansible
* AWS Credentials
* An Ansible Tower License

==== Step 1 - Creating your Own Dark Tower Server or Cluster

. If necessary clone or pull link:https://github.com/redhat-cop/agnosticd.git[AgnosticD]
+
[source,bash]
----
$ git clone https://github.com/redhat-cop/agnosticd.git
----
. Change directory into `agnosticd/ansible`
+
[source,bash]
----
cd agnosticd/ansible
----

. Find the latest `ansible-tower-prod` tag:
+
[source,bash]
----
git tag -l "ansible-tower-prod*" | sort --version-sort | tail -1
----
+
[source,bash]
----
ansible-tower-prod-0.3
----
+
[source,bash]
----
. Checkout the highest/latest revision
git checkout <OUTPUT-OF-THE-PRIOR-COMMAND>
----


==== Preparing the Sample Vars files(s)

The typical way to deploy an AgnosticD config from a control host or laptop is to invoke it with 1, or ideally 2, var files.

NOTE: It is recommeded that you use 2 var files to seperate confidential information such as creds from configuration inofrmation which can be shared freely. That is the pattern we will use here:

+
[source,bash]
----
 ansible-playbook main.yml \
-e @~/dark-tower-vars.yml 
-e @~/secret-vars.yml \
----


. Prepare a `yaml` based variable file 
+
_Sample Babylon Vars File_
+
[source,yaml]
----
---
env_type:                   ansible-tower           # Name of config to deploy
subdomain_base_suffix:      .example.opentlc.com    # Your domain used in FQDN

guid:                       baby-t01                # Unique string used in FQDN
email:                      name@example.com        # User info for notifications, tag

# Deployer meta data

output_dir:                 /tmp/workdir            # Writable working scratch directory

cloud_tags:                                         # Add your tags here
  - Purpose: babylon
  - Stage: dev

# Cloud specfic settings - example given here for AWS

cloud_provider:             ec2                     # Which AgnosticD Cloud Provider to use
aws_region:                 us-east-1               # AWS Region to deploy in
HostedZoneId:               Z3IHLWJZOU9SRT          # You will need to change this
key_name:                   ocpkey                  # Keyname must exist in AWS
cloudformation_retries:     0

# Ansible Tower related vars 

tower_version:              3.5.2-1                 # tower version you want to install 
region:                     na                      # region can not be with special characters in case of isolated node group
software_to_deploy:         tower                   # Define tower to install tower or none to have only infra ready.

tower_instance_count:       1                       # 1 is a legal value (non-cluster), otherwise odd
support_instance_count:     1                       # Postgres database - set to 2 if clustering in same VPC
worker_instance_count:      1                       # Set 0 to not to provision worker(isolated) nodes.

tower_host_name:                "tower1.{{ guid }}{{ subdomain_base_suffix }}" 
tower_user_accounts:            #Define users you want to create. Set superuser: yes to make user system wide System Administrator

  - user: babylon
    password: changeme
    email: babylon@example.com
    firstname: Baby
    lastname: Lon
    superuser: yes

  - user: babylon-viewer
    password: changeme
    email: babylon1@example.com
    firstname: Babylon
    lastname: Viewer

tower_organization:                               # 
  - name: babylon  
  - name: gpte
  - name: ansiblebu
  - name: openshiftbu

target_regions:                                   # These will create instance groups
  - name: default
  - name: na
  - name: apac
  - name: emea

tower_projects:                                   # Tower project

  - name:                     babylon
    description:              Babylon master - main repo
    organization:             "gpte"
    scm_url:                  "https://github.com/redhat-gpte-devopsautomation/babylon.git"
    scm_branch:               master
    scm_update_on_launch:     no
    #scm_type: 
    #scm_credential: 

  - name:                     babylon-dev
    description:              Babylon development branch
    organization:             "gpte"
    scm_url:                  "https://github.com/redhat-gpte-devopsautomation/babylon.git"
    scm_branch:               dev
    scm_update_on_launch:     yes

tower_inventories:

  - name:                     empty-inventory-default
    description:              Default empty inventory for the job runner
    organization:             babylon

  - name:                     empty-inventory-na
    description:              na
    organization:             gpte
    instance_group:           na

  - name:                     empty-inventory-emea
    description:              emea
    organization:             gpte
    instance_group:           emea

tower_credentials:

  - name:                   babylon-tower-credential
    username:               admin
    password:               changeme
    description:            Babylon Tower Credential
    organization:           babylon
    type:                   tower
    state:                  present
    host:                   localhost

tower_job_templates:

  - name:                   job-runner
    description:            "Babylon job-runner - main entry point for all deployers"
    job_type:               run
    project:                babylon
    playbook:               job-runner.yml
    become:                 yes
    inventory:              empty-inventory-default

  - name:                   job-runner-dev
    description:            Babylon job-runner - deploys from head of development branch
    job_type:               run
    project:                babylon-dev
    playbook:               job-runner.yml
    become:                 yes
    inventory:              empty-inventory-default
    verbosity:              3
 
tower_setting_params:               # Tower job settings - Change with CARE
  AWX_PROOT_BASE_PATH:      "/tmp"
  AWX_PROOT_SHOW_PATHS:     "'/var/lib/awx/.ssh', '/var/lib/awx/projects/', '/tmp'"

tower_virtual_environment:      # List of virtual environment which will be created
  - /var/lib/awx/venv/ansible
  - /var/lib/awx/venv/test1

# Path of Virtual Env for update
tower_update_venv:          /var/lib/awx/venv/ansible

# Pip packages with version which needs to be updated for venv
pip_requirements:
  - boto==2.49.0
  - boto3==1.9.200
  - awscli==1.16.210
  - ansible-tower-cli==3.3.6

key_local_path:           ~/.ssh/ocpkey.pem


----
#####
##### SECRET Stuff often stored and passed in a seperate var file
#####

---

own_repo_path: http://my-yum-server/repos

tower_license: >
  {
    "eula_accepted": true,
    "company_name": "Red Hat",
    "hostname": "your-hostname-info-here",
    "instance_count": 500,
    "license_date": 1645192339,
    "license_key": "123456789090193839393939939393939399393993939329393",
    "license_type": "enterprise",
    "subscription_name": "Red Hat Ansible Tower, Standard (50 Managed Nodes)"
  }

# GPTE RW AWS Creds
aws_access_key_id:        <YOUR-AWS-ACCESS-KEY>
aws_secret_access_key:    <YOUR-SECRET-AWS-ACCESS-KEY>
...
----
+
. Deploy your Babylon Tower Config
+
[source,bash]
----
ansible-playbook main.yml -e @<Path-to-my-variable-file>
----

