---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anarchy-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: anarchy-operator
subjects:
- kind: ServiceAccount
  name: anarchy
  namespace: anarchy-operator
