apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: selfpacedlabs.babylon.gpte.redhat.com
spec:
  conversion:
    strategy: None
  group: babylon.gpte.redhat.com
  names:
    kind: SelfPacedLab
    listKind: SelfPacedLabList
    plural: selfpacedlabs
    singular: selfpacedlab
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: >-
          SelfPacedLab definition which provides a portal for users to asynchronously
          claim pre-provisioned lab instances from a warm pool that auto-replenishes.
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*[a-z0-9A-Z])?$
                type: string
            type: object
          spec:
            description: Specification of SelfPacedLab.
            type: object
            properties:
              accessPassword:
                description: >-
                  Optional password for access to the self-paced lab portal.
                type: string
              description:
                description: >-
                  Description text for the self-paced lab.
                type: string
              displayName:
                description: >-
                  Display name for the self-paced lab.
                type: string
              labUserInterface:
                description: >-
                  Default settings for labUserInterface under userAssignments.
                type: object
                properties:
                  redirect:
                    description: >-
                      Configure that users should be automatically redirected to the lab user interface.
                    type: boolean
              lifespan:
                description: >-
                  Lifespan settings for this SelfPacedLab.
                type: object
                properties:
                  end:
                    description: >-
                      End of lifespan for SelfPacedLab and any SelfPacedLabItems that belong to it.
                      After this time the lab is no longer available and resources are cleaned up.
                    type: string
                    format: date-time
                  start:
                    description: >-
                      Start of lifespan for SelfPacedLab. Before this time the lab portal is not available
                      and no provisioning occurs.
                    type: string
                    format: date-time
                  maximum:
                    description: >-
                      Maximum lifespan which may be requested for a self-paced lab relative to its creation.
                    type: string
                    pattern: ^[0-9]+[dhms]$
                  relativeMaximum:
                    description: >-
                      Maximum lifespan which may be requested for a self-paced lab relative to the present date and time.
                    type: string
                    pattern: ^[0-9]+[dhms]$
              multiuserServices:
                description: >-
                  Flag to indicate that services for this self-paced lab are multi-user.
                type: boolean
                default: false
              openRegistration:
                description: >-
                  If set to true then users will not need to be pre-registered and can self-register via the portal.
                type: boolean
                default: true
              provisionDisabled:
                description: >-
                  If set then SelfPacedLabItems are disabled for this SelfPacedLab.
                type: boolean
                default: false
          status:
            description: Status of SelfPacedLab
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              diffBase:
                description: Kopf diffbase
                type: string
              poolCount:
                type: object
                properties:
                  ready:
                    description: Number of unclaimed instances ready for users.
                    type: integer
                  provisioning:
                    description: Number of instances currently being provisioned.
                    type: integer
                  assigned:
                    description: Number of instances assigned to users.
                    type: integer
              resourceClaims:
                description: >-
                  References to ResourceClaims associated with this SelfPacedLab.
                type: object
                additionalProperties:
                  type: object
                  properties:
                    uid:
                      type: string
              selfPacedLabItems:
                description: >-
                  References to SelfPacedLabItems associated with this SelfPacedLab.
                type: object
                additionalProperties:
                  type: object
                  properties:
                    uid:
                      type: string
              selfPacedLabURL:
                description: >-
                  URL for accessing this self-paced lab portal.
                type: string
              userAssignments:
                description: >-
                  References to WorkshopUserAssignments.
                type: object
                additionalProperties:
                  type: object
                  properties:
                    assignment:
                      description: >-
                        Assignment for lab participant.
                      type: object
                      required:
                      - email
                      properties:
                        email:
                          description: >-
                            Email address used to identify lab participant.
                          type: string
                    resourceClaimName:
                      description: >-
                        ResourceClaim name.
                      type: string
                    userName:
                      description: >-
                        User name for lab as reported from the service provisioning.
                      type: string
              userCount:
                type: object
                properties:
                  assigned:
                    description: Assigned users for self-paced lab.
                    type: integer
                  available:
                    description: Available user assignments for self-paced lab.
                    type: integer
                  total:
                    description: Total user assignments for self-paced lab.
                    type: integer
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
