{{- $workshopManager := .Values.workshopManager }}
{{- if and $workshopManager.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-workshop-manager
  annotations:
    description: >-
      Access read cluster resources for babylon workshop-manager
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: workshop-manager
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kopf.dev
  resources:
  - clusterkopfpeerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.catalog.api.group }}
  resources:
  - catalogitems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ $workshopManager.api.group }}
  resources:
  - workshops
  - workshops/status
  - workshopprovisions
  - workshopprovisions/status
  - workshopuserassignments
  - workshopuserassignments/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.resourceBroker.api.group }}
  resources:
  - resourceclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.resourceBroker.api.group }}
  resources:
  - resourcehandles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
