{{- $workshopManager := .Values.workshopManager }}
{{- if and $workshopManager.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: babylon-workshop-manager
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: workshop-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: babylon-workshop-manager
subjects:
- kind: ServiceAccount
  name: babylon-workshop-manager
  namespace: {{ $workshopManager.namespace.name }}
{{- end }}
