{{- $workshopManager := .Values.workshopManager }}
{{- if and $workshopManager.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: babylon-workshop-manager
  namespace: {{ $workshopManager.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: workshop-manager
{{- end }}
