---
# RHPDS virtualenvs -> EE  automatic creation
- name: Override EE with default_execution_environment if not defined
  vars:
    ansible_control_plane: >-
      {{ vars.catalog_item_params.__meta__.ansible_control_plane.type | default('tower') }}

    execution_environment: >-
      {{ vars.catalog_item_params.__meta__.deployer.execution_environment | default({}) }}

    default_execution_environment:
      image: image-registry.apps-dev.open.redhat.com/agnosticd/ee-{{ vars.catalog_item_params.__meta__.deployer.virtualenv | default('ansible2.9-python3.6-2021-11-30') }}
      private: true

    to_merge:
      __meta__:
        deployer:
          execution_environment: "{{ default_execution_environment }}"
  when: >-
    ansible_control_plane == 'controller'
    and execution_environment | default('', true) == ''

  set_fact:
    catalog_item_params: "{{ vars.catalog_item_params | combine(to_merge, recursive=True) }}"
