name: Agnosticv Operator - PR Workflow

on:
  push:
    paths:
      - agnosticv-operator/**
    branches:
      - main
  pull_request:
    paths:
      - agnosticv-operator/**
    branches:
      - main
jobs:
  deploy:
    name: "Publish image in quay"
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      IMAGE_TAGS: ${{ vars.BABYLON_IMAGE_REGISTRY }}/${{ vars.BABYLON_IMAGE_REPOSITORY }}/babylon-agnosticv-operator:${{ github.sha }}
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Set up buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # v1.7.0
        if: env.IMAGE_TAGS
      - name: Login to registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c # v1.9.0
        if: env.IMAGE_TAGS
        with:
          registry: ${{ vars.BABYLON_IMAGE_REGISTRY }}
          username: ${{ secrets.BABYLON_IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.BABYLON_IMAGE_REGISTRY_PASSWORD }}
      - name: Build and publish image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2.10.0
        if: env.IMAGE_TAGS
        with:
          context: agnosticv-operator
          file: agnosticv-operator/Containerfile
          push: true
          tags: ${{ env.IMAGE_TAGS }}
          # images from a PR expire after 14d
          labels: |
            quay.expires-after=14d
