name: Helm Charts - Lint

on:
  pull_request:
    paths:
      - '**/helm/**'
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Configure Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.11.1

      - name: Lint all charts
        run: |
          failed=0
          for chart in $(find . -name Chart.yaml -not -path '*/node_modules/*' -exec dirname {} \;); do
            echo "::group::$chart"
            helm lint "$chart" || failed=1
            echo "::endgroup::"
          done
          exit $failed
