---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agnosticvrepos.gpte.redhat.com
spec:
  group: gpte.redhat.com
  scope: Namespaced
  names:
    kind: AgnosticVRepo
    listKind: AgnosticVReposList
    plural: agnosticvrepos
    singular: agnosticvrepo
    shortNames: []
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: >-
          Settings for configuring Babylon resources from an AgnosticV git repository.
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*[a-z0-9A-Z])?$
          spec:
            description: >-
              Settings for configuring Babylon resources from an AgnosticV git repository.
            type: object
            required:
            - url
            properties:
              babylonAnarchyCollections:
                description: >-
                  List of the galaxy collections required for Babylon Anarchy
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: >-
                        Name of the collection
                      type: string
                    version:
                      description: >-
                        Collection version
                      type: string
              babylonAnarchyRoles:
                description: List of the Babylon Anarchy roles
                type: array
                items:
                  type: object
                  required:
                  - name
                  - src
                  properties:
                    name:
                      description: Name of the role
                      type: string
                    src:
                      description: Url to Git repository
                      type: string
                    version:
                      description: Repository tag
                      type: string
              contextDir:
                description: >-
                  Relative path to directory with AgnosticV repo definitions
                type: string
              default_execution_environment:
                type: object
                properties:
                  image:
                    description: >-
                      Regular expression to match image value to dynamically create execution environment in tower.
                    type: string
                  name:
                    description: >-
                      Image name to use pre-existing images in tower.
                    type: string
                  private:
                    description: >-
                      If set this indicates that the image is private.
                      A credential to pull the image with a name matching the image name must be pre-created in tower.
                    type: boolean
                  pull:
                    description: >-
                      Image pull policy for Ansible controller when dynamically creating execution environment.
                    type: string
                    enum:
                    - always
                    - missing
                    - never
              execution_environment_allow_list_extra:
                type: array
                items:
                  type: object
                  properties:
                    image:
                      description: >-
                        Regular expression to match image value to dynamically create execution environment in tower.
                      type: string
                    name:
                      description: >-
                        Image name to use pre-existing images in tower.
                      type: string
                    private:
                      description: >-
                        If set this indicates that the image is private.
                        A credential to pull the image with a name matching the image name must be pre-created in tower.
                      type: boolean
                    pull:
                      description: >-
                        Image pull policy for Ansible controller when dynamically creating execution environment.
                      type: string
                      enum:
                      - always
                      - missing
                      - never
              gitHub:
                description: >-
                  GitHub integration configuration.
                type: object
                properties:
                  preloadPullRequests:
                    description: >-
                      Configuration to load configuration from open pull requests before merge.
                      This feature is intended for use for integration testing before pull request merge.
                    type: object
                    required:
                    - mode
                    properties:
                      mode:
                        description: >-
                          Pull request pre-load style.
                          In the "override" mode the most recent pull request configuration overrides tho applied component configuration.
                        type: string
                        enum:
                        - override
                  tokenSecret:
                    description: >-
                      Name of secret with GitHub token as `token` in secret data.
                    type: string
              pollingInterval:
                description: >-
                  Polling interval for checking for AgnosticV Repo Updates
                type: string
              ref:
                description: >-
                  Git reference. Ex: branch, commit, or tag
                type: string
              sshKey:
                description: >-
                  Secret name containing Git access key in `id_rsa` data.
                type: string
              url:
                description: >-
                  Url to Git repository containing agnosticv repo definitions
                type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              error:
                description: >-
                  Error details while handling this repository.
                type: object
                properties:
                  message:
                    description: >-
                      Error message.
                    type: string
                  timestamp:
                    description: >-
                      Last timestamp this error was reported.
                    type: string
                    format: date-time
