---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agnosticvcomponents.gpte.redhat.com
spec:
  group: gpte.redhat.com
  scope: Namespaced
  names:
    kind: AgnosticVComponent
    listKind: AgnosticVComponentsList
    plural: agnosticvcomponents
    singular: agnosticvcomponent
    shortNames: []
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: >-
          Merged component definition from AgnosticV.
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
                maxLength: 63
                pattern: ^[a-z][a-z0-9\-._]*$
          spec:
            description: >-
              Rendered component definition from AgnosticV repository.
            type: object
            properties:
              agnosticvRepo:
                description: >-
                  Name of AgnosticVRepo which defined this component.
                type: string
              definition: 
                description: >-
                  Merged component definition from AgnosticV
                type: object
                x-kubernetes-preserve-unknown-fields: true
              path:
                description: >-
                  Component path within AgnosticV repositiory.
                type: string
              pullRequestCommitHash:
                description: >-
                  Pull commit hash if component is managed by a pull request.
                type: string
              pullRequestNumber:
                description: >-
                  Pull request number if component is managed by a pull request.
                type: integer
            required:
            - agnosticvRepo
            - definition
            - path
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
